export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const SET_SHOW_COMPLETE_SIGNUP = "SET_SHOW_COMPLETE_SIGNUP";

export const SET_HCP_BEGIN = "SET_HCP_BEGIN";
export const SET_HCP_SUCCESS = "SET_HCP_SUCCESS";
export const SET_HCP_FAILED = "SET_HCP_FAILED";

export const WEATHER_DATA_REQUESTED = "WEATHER_DATA_REQUESTED";
export const WEATHER_DATA_RETRIEVED = "WEATHER_DATA_RETRIEVED";
export const WEATHER_DATA_FAILED = "WEATHER_DATA_FAILED";

export const FRIEND_DATA_REQUESTED = "FRIEND_DATA_REQUESTED";
export const FRIEND_DATA_RETRIEVED = "FRIEND_DATA_RETRIEVED";
export const FRIEND_DATA_FAILED = "FRIEND_DATA_FAILED";

export const USER_DATA_REQUESTED = "USER_DATA_REQUESTED";
export const USER_DATA_RETRIEVED = "USER_DATA_RETRIEVED";
export const USER_DATA_FAILED = "USER_DATA_FAILED";

export const GOLFCLUB_DATA_REQUESTED = "GOLFCLUB_DATA_REQUESTED";
export const GOLFCLUB_DATA_RETRIEVED = "GOLFCLUB_DATA_RETRIEVED";
export const GOLFCLUB_DATA_FAILED = "GOLFCLUB_DATA_FAILED";

export const FRIEND_REQUEST_SENT = "FRIEND_REQUEST_SENT";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAILED = "FRIEND_REQUEST_FAILED";

export const LOAD_PLAYER = "LOAD_PLAYER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const PENDING_DATA_REQUESTED = "PENDING_DATA_REQUESTED";
export const PENDING_DATA_RETRIEVED = "PENDING_DATA_RETRIEVED";
export const PENDING_DATA_FAILED = "PENDING_DATA_FAILED";

export const RESPOND_FRIEND_BEGIN = "RESPOND_FRIEND_BEGIN";
export const RESPOND_FRIEND_SUCCESS = "RESPOND_FRIEND_SUCCESS";
export const RESPOND_FRIEND_FAILED = "RESPOND_FRIEND_FAILED";

export const ADD_SCORECARD_BEGIN = "ADD_SCORECARD_BEGIN";
export const ADD_SCORECARD_SUCCESS = "ADD_SCORECARD_SUCCESS";
export const ADD_SCORECARD_FAILED = "ADD_SCORECARD_FAILED";

export const SCORECARD_DATA_REQUESTED = "SCORECARD_DATA_REQUESTED";
export const SCORECARD_DATA_RETRIEVED = "SCORECARD_DATA_RETRIEVED";
export const SCORECARD_DATA_FAILED = "SCORECARD_DATA_FAILED";