export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const WEATHER_DATA_REQUESTED = "WEATHER_DATA_REQUESTED";
export const WEATHER_DATA_RETRIEVED = "WEATHER_DATA_RETRIEVED";
export const WEATHER_DATA_FAILED = "WEATHER_DATA_FAILED";
