export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const WEATHER_DATA_REQUESTED = "WEATHER_DATA_REQUESTED";
export const WEATHER_DATA_RETRIEVED = "WEATHER_DATA_RETRIEVED";
export const WEATHER_DATA_FAILED = "WEATHER_DATA_FAILED";

export const FRIEND_DATA_REQUESTED = "FRIEND_DATA_REQUESTED";
export const FRIEND_DATA_RETRIEVED = "FRIEND_DATA_RETRIEVED";
export const FRIEND_DATA_FAILED = "FRIEND_DATA_FAILED";

export const USER_DATA_REQUESTED = "USER_DATA_REQUESTED";
export const USER_DATA_RETRIEVED = "USER_DATA_RETRIEVED";
export const USER_DATA_FAILED = "USER_DATA_FAILED";

export const GOLFCLUB_DATA_REQUESTED = "GOLFCLUB_DATA_REQUESTED";
export const GOLFCLUB_DATA_RETRIEVED = "GOLFCLUB_DATA_RETRIEVED";
export const GOLFCLUB_DATA_FAILED = "GOLFCLUB_DATA_FAILED";

export const FRIEND_REQUEST_SENT = "FRIEND_REQUEST_SENT";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAILED = "FRIEND_REQUEST_FAILED";

export const PLAYER_ADDED = "PLAYER_ADDED";
export const PLAYER_DELETED = "PLAYER_DELETED";
